spring:
  # VSCodeのログの設定
  output:
   ansi:
     enabled: always
  # DBの設定
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/conditions
    username: postgres
    password: postgres